image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  DJANGO: django-app
  REACT: react-lib
  IMAGE_TAG_REACT_ROUTER_BACKEND: $CI_REGISTRY_IMAGE/react-router/backend:$CI_COMMIT_REF_SLUG
  IMAGE_TAG_REACT_ROUTER_FRONTEND: $CI_REGISTRY_IMAGE/react-router/frontend:$CI_COMMIT_REF_SLUG
  IMAGE_TAG_NEXT_BACKEND: $CI_REGISTRY_IMAGE/next/backend:$CI_COMMIT_REF_SLUG
  IMAGE_TAG_NEXT_FRONTEND: $CI_REGISTRY_IMAGE/next/frontend:$CI_COMMIT_REF_SLUG
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_API_VERSION: "1.39"

stages:
  - lint
  - test
  - build
  - e2e
  - deploy

services:
  - docker:18.09-dind

lint-django:
  image: python:3.7-slim
  stage: lint
  except:
    - tags
  tags:
    - low-load
  before_script:
    - pip install black
  script:
    - black --check $DJANGO/**/*.py --exclude .*/migrations/.*

lint-react:
  image: node:13
  stage: lint
  except:
    - tags
  tags:
    - low-load
  before_script:
    - yarn install --pure-lockfile --cwd $REACT
  script:
    - yarn lint --cwd $REACT

unit-test-django:
  image: python:3.7-slim
  stage: test
  except:
    - tags
  dependencies:
    - lint-django
  tags:
    - normal-load
  before_script:
    - cd $DJANGO
    - pip install -U pip pipenv
    - pipenv install --deploy --system -d
  script:
    - python runtests.py

unit-test-react:
  image: node:13
  stage: test
  except:
    - tags
  dependencies:
    - lint-react
  tags:
    - normal-load
  before_script:
    - yarn install --pure-lockfile --cwd $REACT
  script:
    - yarn test --cwd $REACT

build-react-router-backend:
  stage: build
  except:
    - tags
  dependencies:
    - unit-test-django
  tags:
    - normal-load
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#using-docker-caching
    - docker pull $CI_REGISTRY_IMAGE/react-router/backend:develop || true
    - docker build --cache-from $CI_REGISTRY_IMAGE/react-router/backend:develop -t $IMAGE_TAG_REACT_ROUTER_BACKEND --file ./examples/react-router/backend/Dockerfile ./
    - docker push $IMAGE_TAG_REACT_ROUTER_BACKEND

build-react-router-frontend:
  stage: build
  except:
    - tags
  dependencies:
    - unit-test-react
  tags:
    - normal-load
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/react-router/frontend:develop || true
    - docker build --cache-from $CI_REGISTRY_IMAGE/react-router/frontend:develop -t $IMAGE_TAG_REACT_ROUTER_FRONTEND --build-arg app_env=production --file ./examples/react-router/frontend/Dockerfile ./
    - docker push $IMAGE_TAG_REACT_ROUTER_FRONTEND

e2e-test-react-router:
  stage: e2e
  except:
    - tags
  dependencies:
    - build-react-router-backend
    - build-react-router-frontend
  tags:
    - high-load
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-screenshots"
    expire_in: 1 week
    when: always
    paths:
      - screenshots/
      - videos/
    reports:
      junit: test-reports/reporter*.xml
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE_TAG_REACT_ROUTER_FRONTEND
    - docker run -d -p 3000:5000 $IMAGE_TAG_REACT_ROUTER_FRONTEND bash -c ./run.sh
    - docker pull $IMAGE_TAG_REACT_ROUTER_BACKEND
    - docker run -d -p 8000:8000 -e DJANGO_SESSION_COOKIE_SECURE=False -e DJANGO_CACHE_BACKEND=local $IMAGE_TAG_REACT_ROUTER_BACKEND ./run_backend.sh loadfixtures
    - docker run --rm
      -v ${PWD}/cypress/cypress:/app/cypress
      -v ${PWD}/cypress/cypress.json:/app/cypress.json
      -v ${PWD}/cypress/package.json:/app/package.json
      -v ${PWD}/screenshots:/app/cypress/screenshots
      -v ${PWD}/videos:/app/cypress/videos
      -v ${PWD}/test-reports:/app/cypress/results
      --network="host"
      --ipc=host
      ambientinnovation/cypress-docker:latest
      bash -c "yarn install && cypress run --browser chrome"

build-next-backend:
  stage: build
  except:
    - tags
  dependencies:
    - unit-test-django
  tags:
    - normal-load
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#using-docker-caching
    - docker pull $CI_REGISTRY_IMAGE/next/backend:develop || true
    - docker build --cache-from $CI_REGISTRY_IMAGE/next/backend:develop -t $IMAGE_TAG_NEXT_BACKEND --file ./examples/nextjs/backend/Dockerfile ./
    - docker push $IMAGE_TAG_NEXT_BACKEND

build-next-frontend:
  stage: build
  except:
    - tags
  dependencies:
    - unit-test-react
  tags:
    - normal-load
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/next/frontend:develop || true
    - docker build --cache-from $CI_REGISTRY_IMAGE/next/frontend:develop -t $IMAGE_TAG_NEXT_FRONTEND --build-arg app_env=production --file ./examples/nextjs/frontend/Dockerfile ./
    - docker push $IMAGE_TAG_NEXT_FRONTEND

e2e-next-router:
  stage: e2e
  except:
    - tags
  dependencies:
    - build-next-backend
    - build-next-frontend
  tags:
    - high-load
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME-screenshots"
    expire_in: 1 week
    when: always
    paths:
      - screenshots/
      - videos/
    reports:
      junit: test-reports/reporter*.xml
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE_TAG_NEXT_FRONTEND
    - docker run -d -p 3000:5000 $IMAGE_TAG_REACT_ROUTER_FRONTEND bash -c ./run.sh
    - docker pull $IMAGE_TAG_NEXT_BACKEND
    - docker run -d -p 8000:8000 -e DJANGO_SESSION_COOKIE_SECURE=False -e DJANGO_CACHE_BACKEND=local $IMAGE_TAG_NEXT_BACKEND ./run_backend.sh loadfixtures
    - docker run --rm
      -v ${PWD}/cypress/cypress:/app/cypress
      -v ${PWD}/cypress/cypress.json:/app/cypress.json
      -v ${PWD}/cypress/package.json:/app/package.json
      -v ${PWD}/screenshots:/app/cypress/screenshots
      -v ${PWD}/videos:/app/cypress/videos
      -v ${PWD}/test-reports:/app/cypress/results
      --network="host"
      --ipc=host
      ambientinnovation/cypress-docker:latest
      bash -c "yarn install && cypress run --browser chrome"

deploy-react:
  image: node:12
  stage: deploy
  except:
    - tags
  dependencies:
    - unit-test-react
  variables:
    GITLAB_URL: gitlab.ambient-innovation.com
  only:
    - master
  tags:
    - low-load
  before_script:
    - yarn install --pure-lockfile --cwd $REACT
  script:
    - cd $REACT
    - yarn build
    - npx semantic-release

deploy-django:
  image: python:3.7-slim
  stage: deploy
  except:
    - tags
  dependencies:
    - unit-test-django
  variables:
    PYPI_USERNAME: ambient-innovation
  only:
    - master
  tags:
    - low-load
  before_script:
    - apt-get update && apt-get install -y git
    - git config --global user.name "semantic-release"
    - git config --global user.email "hello@ambient-innovation.com"
    - cd $DJANGO
    - pip install -U pip pipenv
    - pipenv install --deploy --system -d
  script:
    - semantic-release publish
