image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  DJANGO: django-ai-kit-auth
  REACT: ai-kit-auth
  IMAGE_TAG_BACKEND: $CI_REGISTRY_IMAGE/django-ai-kit-auth:$CI_COMMIT_REF_SLUG
  IMAGE_TAG_FRONTEND: $CI_REGISTRY_IMAGE/ai-kit-auth:$CI_COMMIT_REF_SLUG
  DOCKER_HOST: tcp://localhost:2375

stages:
  - lint
  - build
  - test
  - deploy

services:
  - docker:18.09-dind

lint-django:
  image: python:3.7-slim
  stage: lint
  tags:
    - low-load
  before_script:
    - pip install black
  script:
    - black --check $DJANGO/**/*.py --exclude .*/migrations/.*

lint-react:
  image: node:13
  stage: lint
  tags:
    - low-load
  before_script:
    - npm ci --prefix $REACT
  script:
    - npm run --prefix $REACT lint

unit-test-django:
  image: python:3.7-slim
  stage: test
  dependencies:
    - lint-django
  tags:
    - normal-load
  before_script:
    - cd $DJANGO
    - pip install -U pip pipenv
    - pipenv install --deploy --system -d
  script:
    - python runtests.py

unit-test-react:
  image: node:13
  stage: test
  dependencies:
    - lint-react
  tags:
    - normal-load
  before_script:
    - npm ci --prefix $REACT
  script:
    - npm test --prefix $REACT

deploy-react:
  image: node:13
  stage: deploy
  dependencies:
    - unit-test-react
  variables:
    GITLAB_URL: gitlab.ambient-innovation.com
  only:
    - master
  tags:
    - low-load
  before_script:
    - npm ci --prefix $REACT
  script:
    - cd ai-kit-auth
    - npm run build
    - npx semantic-release

deploy-django:
  image: python:3.7-slim
  stage: deploy
  dependencies:
    - unit-test-django
  variables:
    PYPI_USERNAME: ambient-innovation
  only:
    - master
  tags:
    - low-load
  before_script:
    - cd $DJANGO
    - pip install -U pip pipenv
    - pipenv install --deploy --system -d
    - apt-get update && apt-get install -y git
    - git config --global user.name "semantic-release"
    - git config --global user.email "hello@ambient-innovation.com"
    - cd python_commit_parser && python setup.py install && cd ..
  script:
    - semantic-release publish
