# Basic set up for three package managers
version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/react-lib"
    schedule:
      interval: "daily"
    reviewers:
      - edward.lecock
      - ronny.vedrilla
  - package-ecosystem: "pip"
    directory: "/django-app"
    schedule:
      interval: "daily"
    reviewers:
      - edward.lecock
      - ronny.vedrilla
